### ISSUE TITLE
Module not found on CPAN

### ISSUE THREAD

**Issue by Azq2** [dams/params-check-faster#1]
http://search.cpan.org/perldoc?Params::Check::Faster
404

Why?

**Comment by dams** [comment]
do you require it ? if yes, for which code ?

**Comment by ghost** [comment]
I require it.
For checking parameters of big and complex functions.

**Comment by dams** [comment]
OK, sorry abotu that I'll add it back on CPAN. Thanks for using it

**Comment by dams** [comment]
Re-uploaded on CPAN with version 0.04. Should be visible soone. Reopen the bug if you still can't find it.

**Comment by ghost** [comment]
Thank you very match.
